### ISSUE TITLE
Development roadmap 

### ISSUE THREAD

**Issue by epogrebnyak** [finec-mgimo/chatbot#7]
Сделано:

- [x] бота можно запускать локально и в командной строке на AWS EC2
- [x] найден прокси для работы с 
- [x] бот отвечает на две команды
- [x] опробован деплой на [EB](#6)

Work in progress (WIP):

- [ ] перейти на webhook
- [ ] деплоить на EC2, задокументировать 
- [ ] сделать код/конфигурацию для EB

Особенности:

- [ ] сейчас это pooling программа, а не webhook

Ограничения:

- [ ] нет хранения данных (без памяти)
- [ ] только команды, нет понимания речи
- [ ] нет тестов

Перспектива:

- [ ] новые фичи бота (бот для поступающих)
